version: '3.8'  # Cập nhật phiên bản docker-compose nếu cần

services:
  zookeeper:
    image: bitnami/zookeeper:latest  # Hình ảnh Zookeeper mới
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest  # Hình ảnh Kafka chính thức
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
confluentinc