version: "3.3"

services:
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_PORT: 8088
      SUPERSET_DB__BACKEND: postgresql
      SUPERSET_DB__HOST: db
      SUPERSET_DB__PORT: 5432
      SUPERSET_DB__USER: superset
      SUPERSET_DB__PASSWORD: superset
      SUPERSET_DB__NAME: superset
    depends_on:
      - db
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py  # Gắn file vào container
    restart: always

  # db:
  #   image: postgres:15
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: superset
  #     POSTGRES_PASSWORD: superset
  #     POSTGRES_DB: superset
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: always

volumes:
  superset_home:
  postgres_data:
