version: '3.8'

services:
  superset:
    build: .
    container_name: superset_app
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_SECRET_KEY: "zQ+E6kxsQUK9xldHo9xz1U5YPJqa1R2j9XZlp8NfMv2HoH3oT8dNKD1GHM2QK/So"
    volumes:
      - ./superset_home:/app/superset_home
      - ./data:/app/data
    command:
      - "superset fab create-admin --username admin --password admin --firstname Admin --lastname User --email admin@admin.com && superset db upgrade && superset init && superset run -h 0.0.0.0 -p 8088"

volumes:
  superset_home:
