version: "3.9"
services:
  superset:
    image: apache/superset:latest
    container_name: superset_app
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - ./superset_home:/app/superset_home
    environment:
      SUPERSET_CONFIG_PATH: /app/superset_home/superset_config.py

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: superset_user
      POSTGRES_PASSWORD: superset_password
      POSTGRES_DB: superset_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
